[package]
name = "cli_chomper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4.38"
aes = "0.8.4"
hex = "0.4"
